name: UMPy

dependencies:
  - python>3.7,<3.11
  - numpy>=1.21,<=1.26.4
  - matplotlib
  - pip
  - pip:
    - scipy
    - pandas
    - mtscomp
    - jobLib
    - tk
    - mat73
    - tqdm
    - spikeinterface
    - h5py
    - scikit-learn
    - torch
    - ipykernel
